services:
  ghosler:
    image: itznotabug/ghosler
    container_name: ghosler
    ports:
      - "2369:2369"
    volumes:
      - logs:/usr/src/app/.logs
      - analytics:/usr/src/app/files
      - configuration:/usr/src/app/configuration
    environment:
      NODE_ENV: production

volumes:
  logs:
  analytics:
  configuration: